### ISSUE TITLE
logiled inactive

### ISSUE THREAD

**Issue by Bassist067** [HunterZ/UniLight#1]
Hi HunterZ, first, thank you for the nice software for RGB freaks. 

Can you please guide me? I've got Alienware 17 R4 + Logitech G910 Orion Spectrum keyboard + Logitech G933 Artemis Spectrum Snow. 

For Alienware, Unilight works nicely and shows "Active" in tray. For Logitech, though, it's showing "Inactive" and doesn't work. Can you please show where should I search? I'm a .NET developer, so my C++ skill is low.

Thanks again!

**Comment by HunterZ** [comment]
Odd, I use it with an Alienware 17R3 and Logitech G502 Proteus Spectrum.

Do you have the latest Logitech Gaming Software installed and running? I'm currently using 8.96.88.

**Comment by Bassist067** [comment]
oh yes, LGS is running with the latest version. I thought maybe it's about the headphones, but it's not. I guess I need to compile and debug the thing, but under VS2017 it's difficult to compile

**Comment by HunterZ** [comment]
Do you have a C:\Program Files\Logitech Gaming Software\SDK\LED\x86\LogitechLed.dll file on your system? What version does it show if you right-click it in Explorer and open its properties?

Do you have the following Windows Registry entries with default values containing the above path:
HKEY_CLASSES_ROOT\CLSID\{a6519e67-7632-4375-afdf-caa889744403}\ServerBinary
HKEY_CLASSES_ROOT\Wow6432Node\CLSID\{a6519e67-7632-4375-afdf-caa889744403}\ServerBinary
HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{a6519e67-7632-4375-afdf-caa889744403}\ServerBinary
HKEY_LOCAL_MACHINE\SOFTWARE\Classes\WOW6432Node\CLSID\{a6519e67-7632-4375-afdf-caa889744403}\ServerBinary
HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Classes\CLSID\{a6519e67-7632-4375-afdf-caa889744403}\ServerBinary

If you get it compiling, you may want to try messing with this line in LLEDUtil.cpp to see if it makes a difference:
```cpp
if (!LogiLedSetTargetDevice(LOGI_DEVICETYPE_PERKEY_RGB | LOGI_DEVICETYPE_RGB)) return false;
```
In particular, this might be worth trying:
```cpp
if (!LogiLedSetTargetDevice(LOGI_DEVICETYPE_ALL)) return false;
```
I put that in to have it leave monochrome devices alone, but it's possible that Logitech messed up their categorization of your device(s).

Looking at LLEDUtil.cpp again after not having touched it for several months, I see some slightly goofy stuff in there, but I don't see anything that would cause your issue.

Looking at the SDK documentation again (https://www.logitechg.com/en-us/developers), another application initializing the RGB SDK after UniLight is launched may cause it to lose control. I don't aggressively try to take back control but maybe I should? Part of the reason I didn't make it aggressive is because Logitech mentions some stupid stuff about needing to wait some undefined amount of time between initializing the SDK and trying to do anything with it, so I was worried that trying to (re)init every time I want to set the colors would end up not working.

Edit: I probably ought to put a timer back into UniLight to have it try to re-set the color every so often, which I could then use to do Logitech (re)inits+delays as well. This might also help with the fact that UniLight seems to lose its AlienFX/LightFX connection after a while for some reason. I used to run UniLight exclusively on a timer, but then I found some Windows events I could drive it from instead, which is better for performance reasons.

**Comment by RetroL** [comment]
Hello there.

So, i also have a problem which looks a bit like this one.
When i open UniLight, my keyboard and my mouse ( They're both Logitech, g810 and g403 wireless ) lights in blue. When i mouseover UniLight in the Windows system tray, i can read : 
"UniLight status:
Current color: 0x00c76f00
Previous color: 0x00000000
CorsCUE: inactive
LightFX: inactive
LogiLED: active"
When i use "Synchronize manually", the color remains the same. 
When i open UniLight, even with a red picture on my screen, the color is always "0x00c76f00".

My LogitechLed.dll version is 8.96.88, i checked all the Windows registry entries, and they all have the  default values.

I tried to be as precise as possible, tell me if something is missing. :)

**Comment by HunterZ** [comment]
RetroL: Your issue may be slightly different, as you get "active" for LogiLED.

Your DLL is 8.96.88, or is that your LGS version? My LGS version is 8.96.88, but my C:\Program Files\Logitech Gaming Software\SDK\LED\x86\LogitechLed.dll is 8.96.81.0.

What version of Windows are you running?

**Comment by RetroL** [comment]
My DLL version is 8.96.88.0 and my LGS version is 8.96.88.
I run Windows 10 Family, the version is 1709, and the operating system version is 16299.248
![windows version](https://user-images.githubusercontent.com/36845767/36802113-36b6315e-1cb4-11e8-8692-92661f07cf8e.PNG)
![logitech capture](https://user-images.githubusercontent.com/36845767/36802147-701b251c-1cb4-11e8-949f-c084c5d38a75.PNG)
( The screenshots are in french, but it should be understandable )

**Comment by HunterZ** [comment]
LGS said I have the latest version installed, but my DLL version was lower than yours.

I shut down UniLight and re-downloaded and reinstalled the latest LGS from Logitech's web site, and now I have LogitechLed.dll 8.96.88.0. UniLight still works for me, so the problem must be something else.

Maybe try closing any apps that have LED support and then reinstall the latest LGS from Logitech's web site? http://support.logitech.com/en_us/software/lgs

In the meantime, I'm writing an email to Logitech's developer support to see if they have any ideas.

Edit: I also double-checked that I have the latest Logitech gaming SDK, so I don't think it's an issue of building against old stuff.

**Comment by HunterZ** [comment]
Update:

Logitech got back to me. The main thing they wanted me to check on is that you guys have "Allow games to control illumination" enabled in LGS:
![image](https://user-images.githubusercontent.com/108939/37318641-d6e803fa-2628-11e8-8add-a7ae0b941c12.png)

They also pointed out some minor issues with my code that they don't expect are causing the issue, but I'll try to get them fixed anyway just in case.

**Comment by HunterZ** [comment]
OK, I've released v1.3 with some cleanups to the Logitech support. Let me know how things go for you.

**Comment by RetroL** [comment]
I just tried the new version 1.3, and the problem is still there, with the same color ( 0x00c76f00 )
"Allow games to control illumination" was already checked for me, i tried to turn it off and on, but it didn't do anything.

**Comment by HunterZ** [comment]
I've released a version 1.4 that adds a right-click menu to open a popup with detailed status. Can you try running this and posting a screenshot?

**Comment by Bassist067** [comment]
How can I download the release version? Or how can I compile the solution - it looks like you didn't include the SDKs DLLs and headers. Thanks in advance - you're doing a great job!

**Comment by HunterZ** [comment]
Releases are here: https://github.com/HunterZ/UniLight/releases

The file you want is UniLight_v1.4.zip

I'll create an issue to add links in the readme to where the SDKs are provided by their respective companies.

**Comment by RetroL** [comment]
Hey, here is the screenshot i took :
![00000screenshot unilight](https://user-images.githubusercontent.com/36845767/37922033-c9a3face-312b-11e8-983b-f97a466a52e5.PNG)

**Comment by Bassist067** [comment]
![image](https://user-images.githubusercontent.com/19996164/37922759-b09d7434-3157-11e8-9bc1-60e252e463fa.png)

**Comment by HunterZ** [comment]
RetroL: It looks like the Logitech API is reporting success at setting the colors for you, so it seems that there must be something outside of UniLight that is overriding it.

Bassist067: UniLight is reporting that its call to the Logitech API to initialize Logitech LED support is failing. This is the first thing that UniLight does when it starts up, so something fundamental is wrong. Are you able to control your device colors from the Logitech Gaming Software app?

**Comment by Bassist067** [comment]
The Logitech software works nice for me - I can easily sync my L gear or use all the G910 different light modes. I'll try to install all the SDK and compile the project

**Comment by HunterZ** [comment]
I've updated README.md with tool/SDK links.

You probably already have the AlienFX SDK because I think it comes with Alienware Command Center or whatever.
